# makefile
# 
# Name: Aleksandar Ilic
# NetID: ailic3
# 
# Homework #4
# Group: 20
# CS 342, FALL 2018, CRN: 37162
# November 14, 2018
# 
# This makefile is intended to compile all Java class files associated with
# Homework #4. Files to be compiled include:
#
# The following commands may be invoked:
#
#					- compile:  Compiles all .java files.
#					- run:		Runs the Homework Assignment (without command-line input)
#					- clean:	Deletes all .class files.
# 

compile:
	javac *.java

run:
	java GameTester

clean:
	rm -f *.class